# Generated by Django 6.0.2 on 2026-03-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_end_time_alter_task_init_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='init_time',
            field=models.TimeField(verbose_name='Init time'),
        ),
    ]
